### ISSUE TITLE
uhhhhhhhhhh

### ISSUE THREAD

**Issue by Bloctans** [HackerPoet/HyperEngine#1]
![image](https://user-images.githubusercontent.com/93960460/164877858-64297524-5f07-411c-a661-45a0483e9c94.png)
Wondering if this is related to updating to the new input system? I think it is?

**Comment by Bloctans** [comment]
yeah think it is.

**Comment by clarfonthey** [comment]
FWIW these kinds of things are better as discord messages than issue reports. These kinds of things aren't really useful here on GitHub and they just clutter up stuff for folks who follow the repository for other reasons.
